### ISSUE TITLE
Security Incident - AA-001

### ISSUE THREAD

**Issue by akirarorschach** [CubeLordDevs/CubeLord2.0#10]
We are confirming a compromise with Cubelord 2.0. The bot is down for a security investigation and will remain so until the security breach is resolved. 

We apologize for this inconvenience and will release a postmortem statement.

**Comment by Dodesimo** [comment]
ok

**Comment by akirarorschach** [comment]
PRESS RELEASE AB-001 on the security incident: [https://docs.google.com/document/d/1HhlTiIO-E93OW4V4P3Usz3xU5Ke9n6OVSP4ZfCH-XvA/edit?usp=sharing](https://docs.google.com/document/d/1HhlTiIO-E93OW4V4P3Usz3xU5Ke9n6OVSP4ZfCH-XvA/edit?usp=sharing)
