### ISSUE TITLE
warning/banning someone yields obscure error.

### ISSUE THREAD

**Issue by Dodesimo** [CubeLordDevs/CubeLord2.0#8]
when trying to ban/kick somone, cubelord leaves behind an obscure error message, and ultimately the commands don't work. THIS HAS TO BE FIXED ASAP, otherwise current servers using the bot will suffer.

error message: "Subreddit not found"

**Comment by Redapple8787** [comment]
What is the exception?

**Comment by Dodesimo** [comment]
^check OP for edit

**Comment by Dodesimo** [comment]
issue fixed; was a simple permission hierarchy fix. CubeLord2.0 role needs to be at the top of all the other roles within the "Roles" section for all of its commands to work.
